apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnsadmin
  namespace: {{NAMESPACE}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dnsadmin
  namespace: {{NAMESPACE}}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{AXFR_SECRET_NAME}}"]
    verbs: ["get", "update", "patch"]
{{CERT_MANAGER_RBAC}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dnsadmin
  namespace: {{NAMESPACE}}
subjects:
  - kind: ServiceAccount
    name: dnsadmin
    namespace: {{NAMESPACE}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dnsadmin
