apiVersion: v1
kind: Secret
metadata:
  name: dnsadmin-auth
  namespace: {{NAMESPACE}}
type: Opaque
stringData:
  ADMIN_USERNAME: {{ADMIN_USERNAME}}
  ADMIN_PASSWORD: {{ADMIN_PASSWORD}}
  JWT_SECRET: {{JWT_SECRET}}
