server:
  listen: 0.0.0.0@53
  identity: ns2.example.test
  nsid: ns2.example.test

log:
  - target: stdout
    any: info

database:
  storage: /var/lib/knot

key:
  - id: playground-tsig
    algorithm: hmac-sha256
    secret: cGxheWdyb3VuZC10c2lnLWtleS1mb3ItdGVzdGluZy1vbmx5IQ==

remote:
  - id: primary
    address: 172.30.0.10@53
    key: playground-tsig

acl:
  - id: notify-allowed
    action: notify
    key: playground-tsig

# Принудительный поллинг primary каждые 4 часа при потере связи
zone-defaults:
  refresh-min-interval: 14400
  refresh-max-interval: 86400

zone:
  - domain: example.test
    master: primary
    acl: [notify-allowed]

  - domain: playground.local
    master: primary
    acl: [notify-allowed]

  - domain: db.test
    master: primary
    acl: [notify-allowed]
