apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsadmin-namespace-reader
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dnsadmin-namespace-reader
subjects:
  - kind: ServiceAccount
    name: dnsadmin
    namespace: dns-knot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dnsadmin-namespace-reader
