apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: {{WEBHOOK_VERSION}}.{{WEBHOOK_GROUP_NAME}}
spec:
  group: {{WEBHOOK_GROUP_NAME}}
  version: {{WEBHOOK_VERSION}}
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    namespace: {{NAMESPACE}}
    name: dnsadmin
    port: 443
  caBundle: {{WEBHOOK_CA_BUNDLE}}
